IN_RESOURCE_APPLICATION_KEY: IN_RESOURCE_APPLICATION_VALUE
# jushuitan-api/mp-rest/url=https://open.erp321.com
jushuitan-api:
  mp-rest:
    url: https://c.jushuitan.com
    scope: javax.inject.Singleton
# SendToPlugin type in the dcs-plugin-server project.
DCS_TO_PLUGIN: >
  {
    "output_to": {"type": "STDIO", "settings": {"separator": "08877f24-464a-4867-b58c-6b500349dae1"}},
    "plugin_instance": {},
    "state": {}
  }
# https://blog.rpuch.com/2020/09/23/compiling-netty-enabled-application-with-dns-support-to-native-image-in-2020.html
quarkus:
  index-dependency:
  -  name:
     group-id: com.fasterxml.jackson.core
     artifact-id: jackson-core
     classifier:
  - name1:
     group-id: org.jboss.logging
     artifact-id: jboss-logging
     classifier:
  - name2:
    group-id: org.apache.kudu
    artifact-id: kudu-client
    classifer:
  package:
    type: uber-jar
  # log:
  #   level: ERROR
    # category:
    #   io.qua.config:
    #     level: ERROR
  native:
    additional-build-args:
      - --trace-class-initialization=io.netty.resolver.dns.DnsNameResolver,io.netty.resolver.HostsFileEntriesResolver,io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder
      - --initialize-at-build-time=io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder,io.netty.resolver.dns.DnsNameResolver,io.netty.resolver.HostsFileEntriesResolver
kudu:
  master: 161.189.46.49:7051
  