IN_RESOURCE_APPLICATION_KEY: IN_RESOURCE_APPLICATION_VALUE
# jushuitan-api/mp-rest/url=https://open.erp321.com
jushuitan-api:
  mp-rest:
    url: https://c.jushuitan.com
    scope: javax.inject.Singleton
# SendToPlugin type in the dcs-plugin-server project.
DCS_TO_PLUGIN: >
  {
    "output_to": {"type": "STDIO", "settings": {"separator": "08877f24-464a-4867-b58c-6b500349dae1"}},
    "plugin_instance": {},
    "state": {}
  }
quarkus:
  index-dependency:
  -  name:
     group-id: com.fasterxml.jackson.core
     artifact-id: jackson-core
     classifier:
  - name1:
     group-id: org.jboss.logging
     artifact-id: jboss-logging
     classifier:
  package:
    uber-jar: true
kudu:
  master: 161.189.46.49:7051
  