IN_RESOURCE_APPLICATION_KEY: IN_RESOURCE_APPLICATION_VALUE
# jushuitan-api/mp-rest/url=https://open.erp321.com
jushuitan-api/mp-rest/url: https://c.jushuitan.com
jushuitan-api/mp-rest/scope: javax.inject.Singleton

hasura-rest/mp-rest/url:  http://hasura
hasura-rest/mp-rest/scope: javax.inject.Singleton

upload/mp-rest/url:  http://localhost:8080/

hasura:
  admin-secret: Eigh1diech0rohchoodai6Ohjah7uPei
  fixture-dir: c:/Users/jiang/fdatacollect/dcs-plugin-server/fixtures/

# SendToPlugin type in the dcs-plugin-server project.
DCS_TO_PLUGIN: >
  {
    "output_to": {"type": "STDIO", "settings": {"separator": "08877f24-464a-4867-b58c-6b500349dae1"}},
    "plugin_instance": {},
    "state": {}
  }
# https://blog.rpuch.com/2020/09/23/compiling-netty-enabled-application-with-dns-support-to-native-image-in-2020.html
quarkus:
  http:
    host-enabled: false
    # insecure-requests: DISABLED
    # redirect-insecure-requests: abc
  # http:
  #   port: 8081
  # rest-client:
  #   upload:
  #     url: http://localhost:8080/
  index-dependency:
    name:
      group-id: com.fasterxml.jackson.core
      artifact-id: jackson-core
      classifier:
    name1:
       group-id: org.jboss.logging
       artifact-id: jboss-logging
       classifier:
    name2:
      group-id: org.apache.kudu
      artifact-id: kudu-client
      classifer:
  package:
    type: uber-jar
  log:
    level: DEBUG
    category:
      org.jboss.resteasy.microprofile.client: DEBUG
    #   io.qua.config:
    #     level: ERROR
  native:
    additional-build-args:
      - --trace-class-initialization=io.netty.resolver.dns.DnsNameResolver,io.netty.resolver.HostsFileEntriesResolver,io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder
      - --initialize-at-build-time=io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder,io.netty.resolver.dns.DnsNameResolver,io.netty.resolver.HostsFileEntriesResolver
    # extensions-api:
    #   hostname-verifier: io.quarkus.restclient.NoopHostnameVerifier
  # tls:
    # trust-all: true
kudu:
  master: 161.189.46.49:7051
  
apps:
  deploys:
    DCS_PLUGIN_SERVER:
      project-root: C:/Users/jiang/fdatacollect/
      git-url: https://github.com/openscanner/fdatacollect
      build-command: gradlew.bat,build,-x,test
      ssh-connect-str: root@192.168.0.22
      jars-in-dir: dcs-plugin-server/build/libs
