# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: playground for testing

on:
  # release:
  #   types: [created]
  #   # Draft a new release
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: prepare value
      id: strip-v
      run: |
        echo "::set-output name=no_v_prefix::`echo -n 'v0.1.0' | sed -e 's/v//g'`"
    - name: Display version after strip v.
      run: echo "The version has no v ${{ steps.strip-v.outputs.no_v_prefix }}"